spring:
  application:
    name: user-account
  config:
    import: optional:configserver:http://localhost:8888
redis:
  host: localhost
  port: 6379
eureka:
  clietn:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8200
share:
  queue: shareQueue
